name: pds_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.4.0
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.0
  url_launcher: ^6.2.6
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  shared_preferences: ^2.5.3
  go_router: ^15.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/imagecarrosel.jpg
    - assets/imagecarrosel2.jpg
    - assets/imagecarrosel3.jpg
    - assets/logo1.png
    - assets/logo2.png